// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        return linux;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqMn_WiFFsSNNXKCJqf1vKX2rJQnqJaYE',
    appId: '1:574053615024:android:6f97c12579939bf4aac275',
    messagingSenderId: '574053615024',
    projectId: 'norskfuelpriceapp-firebase',
    storageBucket: 'norskfuelpriceapp-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqMn_WiFFsSNNXKCJqf1vKX2rJQnqJaYE',
    appId: '1:574053615024:android:6f97c12579939bf4aac275',
    messagingSenderId: '574053615024',
    projectId: 'norskfuelpriceapp-firebase',
    storageBucket: 'norskfuelpriceapp-firebase.firebasestorage.app',
    iosBundleId: 'no.fueltracker.fuelPriceTracker',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqMn_WiFFsSNNXKCJqf1vKX2rJQnqJaYE',
    appId: '1:574053615024:android:6f97c12579939bf4aac275',
    messagingSenderId: '574053615024',
    projectId: 'norskfuelpriceapp-firebase',
    storageBucket: 'norskfuelpriceapp-firebase.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAqMn_WiFFsSNNXKCJqf1vKX2rJQnqJaYE',
    appId: '1:574053615024:android:6f97c12579939bf4aac275',
    messagingSenderId: '574053615024',
    projectId: 'norskfuelpriceapp-firebase',
    storageBucket: 'norskfuelpriceapp-firebase.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqMn_WiFFsSNNXKCJqf1vKX2rJQnqJaYE',
    appId: '1:574053615024:android:6f97c12579939bf4aac275',
    messagingSenderId: '574053615024',
    projectId: 'norskfuelpriceapp-firebase',
    storageBucket: 'norskfuelpriceapp-firebase.firebasestorage.app',
  );
}
